Add various improvements from current version and upstream RefApp

diff --git a/frontend/Dockerfile b/frontend/Dockerfile
--- a/frontend/Dockerfile
+++ b/frontend/Dockerfile
@@ -2,9 +2,9 @@
 #--------------------------------------------
 # Dev Stage - Assembles and Builds Frontend
 #--------------------------------------------
-FROM --platform=$BUILDPLATFORM node:18-alpine as dev
+FROM --platform=$BUILDPLATFORM node:22-alpine as dev
 
-ARG APP_SHELL_VERSION=next
+ARG APP_SHELL_VERSION=latest
 
 RUN mkdir -p /app
 WORKDIR /app
@@ -13,9 +13,9 @@ COPY spa-assemble-config.json .
 COPY spa-build-config.json .
 
 ARG CACHE_BUST
-RUN npx --legacy-peer-deps openmrs@${APP_SHELL_VERSION:-next} assemble --manifest --mode config --config spa-assemble-config.json --target ./spa
-RUN npx --legacy-peer-deps openmrs@${APP_SHELL_VERSION:-next} build --build-config spa-build-config.json --target ./spa
-RUN if [ ! -f ./spa/index.html ]; then echo 'Build failed. Please check the logs above for details. This may have happened because of an update to a library that OpenMRS depends on.'; exit 1; fi
+RUN npx --legacy-peer-deps openmrs@${APP_SHELL_VERSION:-latest} assemble --manifest --mode config --config spa-assemble-config.json --target ./spa
+RUN npx --legacy-peer-deps openmrs@${APP_SHELL_VERSION:-latest} build --build-config spa-build-config.json --target ./spa
+RUN if [ ! -f ./spa/index.html ]; then echo 'Build failed. Please check the logs above for details. This may have happened because of an update to a library that OpenMRS depends on.'; ls -al ./spa; exit 1; fi
 
 #--------------------------------------------
 # Runtime Stage - Published Image
@@ -23,9 +23,9 @@ RUN if [ ! -f ./spa/index.html ]; then echo 'Build failed. Please check the logs
 FROM nginx:1.25-alpine
 
 RUN apk update && \
-    apk upgrade && \
-    # add more utils for sponge and envsubst
-    apk add --no-cache moreutils
+  apk upgrade && \
+  # add more utils for sponge and envsubst
+  apk add --no-cache moreutils
 
 # clear any default files installed by nginx
 RUN rm -rf /usr/share/nginx/html/*
